name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@13.2
      with:
        cli: '1.12.0.1530'
    - name: Run tests
      run: clojure -M:spec
